name: Terraform VPC

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::881490095131:role/github-dop-project-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
#        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan
#        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
#        working-directory: terraform